---
- hosts: localhost
  tasks:
  - name: "Install Rust Server"
    expect:
      command: "runuser -l rustserver -c '~/./rustserver install'"
      responses:
        (?i)[Y/n] : ""
      timeout: null