---
- hosts: localhost
  tasks:
  - name: "Install RustServer"
    expect:
      command: "runuser -l rustserver -c '~/./rustserver install'"
      responses:
        Question:
          - Continue? [Y/n] : "Y"
          - Was the install successful? [Y/n] : "Y"
          - Allow anonymous usage statistics? [Y/n] : "Y"