---
- hosts: localhost
  tasks:
  - name: "Install RustServer"
    expect:
      command: "runuser -l rustserver -c '~/./rustserver install'"
      responses:
        (?i)[Y/n] : ""
        (?i)[Y/n] : ""
        (?i)[Y/n] : ""
      ignore_errors: yes