---
- hosts: localhost
  tasks:
  - name: "Creating a user: rustserver"
    shell: "adduser rustserver"
  - name: "Install Rust Script"
    shell: "whoami"
    become: true
    become_user: rustserver
    become_method: su