---
- hosts: localhost
  tasks:
  - name: "Making directory"
    shell: mkdir -p /opt/server/logs /opt/server/steam_install
  - name: "Download SteamCMD"
    get_url:
      url: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
      dest: "/opt/server/steam_install/steamcmd_linux.tar.gz"
      mode: '0750'
  - name: "Unarchive SteamCMD"
    unarchive:
      src: "/opt/server/steam_install/steamcmd_linux.tar.gz"
      dest: "/opt/server/steam_install/"
      remote_src: yes
  - name: "Remove steamcmd tar extraction no longer needed"
    file:
      path: "/opt/server/steam_install/steamcmd_linux.tar.gz"
      state: absent
  - name: "Installing Rust Server: /opt/server/rustserver"
    shell: "/opt/server/steam_install/./steamcmd.sh +login anonymous +force_install_dir /opt/server/rustserver +app_update 258550 -validate +quit"
