---
- hosts: localhost
  tasks:
  - name: "Download Oxide Installer"
    get_url:
      url: https://umod.org/games/rust/download/develop
      dest: "/opt/server/oxide_install.zip"
      mode: '0640'
  - name: "Unarchive Oxide Installer"
    unarchive:
      src: "/opt/server/oxide_install.zip"
      dest: "/opt/server/rustserver/"
      remote_src: yes
  - name: "Remove Oxide Installer"
    file:
      path: "/opt/server/oxide_install.zip"
      state: absent