---
- hosts: localhost
  tasks:
  - name: "Download Plugin"
    get_url:
      url: http://umod.org/plugins/{{plugin_name}}.cs
      dest: "/opt/server/rustserver/oxide/plugins/{{plugin_name}}.cs"
      mode: '0750'