---
- hosts: localhost
  tasks:
  - name: "Updating Game Server"
    shell: "/opt/rustserver/steam_install/./steamcmd.sh +login anonymous +force_install_dir /opt/server/rustserver/ +app_update 258550 -validate +quit"