---
- hosts: localhost
  tasks:
  - name: "Install prerequisites for {{game_server}}"
    yum:
      name:
        - curl
        - wget
        - tar
        - bzip2
        - gzip
        - unzip
        - python3
        - binutils
        - bc
        - jq
        - tmux
        - glibc.i686
        - libstdc++
        - libstdc++.i686
        - zlib-devel
        - file
        - nmap-ncat.x86_64
      state: latest